[phases.setup]
nixPkgs = ["python310", "python310Packages.pip"]

[phases.install]
cmds = [
  "pip install --user --upgrade pip",
  "pip install --user numpy==1.26.4",
  "pip install --user -r requirements.txt"
]

[start]
cmd = "gunicorn app_nodb:app"